# Generated by Django 5.1.5 on 2025-01-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='todo_list_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='todo_list_state',
            field=models.CharField(blank=True, choices=[('ID', 'Waiting for todo list ID'), (None, 'No active todo list')], max_length=2, null=True),
        ),
    ]
